"""Seed the intel_teams collection with the standard organisational team roster.

Run from the project root:
    python seed_intel_teams.py [--clear]

--clear  Drop all existing intel_teams before inserting (default: skip duplicates).
"""

import sys
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from intelligence.models import IntelTeam
from intelligence.store import IntelTeamStore

TEAMS = [
    ("Regulatory Compliance Team", "Within the Compliance department, the Regulatory Compliance Team serves as the organization's central function for interpreting RBI and other applicable regulatory requirements, converting them into practical internal actions, and coordinating implementation across Legal, Risk, Operations, Finance, Technology, Product, and business teams. It continuously monitors compliance through control testing, gap assessments, remediation tracking, and audit-ready documentation, while also maintaining clear evidence trails that demonstrate adherence. By translating changing regulations into operational expectations and ensuring follow-through across the enterprise, this team helps leadership protect the organization from regulatory breaches, penalties, and reputational risk.", "Compliance"),
    ("Policy & Governance Team", "Within the Compliance department, the Policy & Governance Team builds the internal rulebook that guides how the entire organization operates in a controlled, accountable, and regulator-ready manner. It designs and updates policies, SOPs, governance structures, approval matrices, and escalation frameworks so that business, Operations, Risk, Finance, Technology, HR, and Product teams can work with consistent standards and clearly defined responsibilities. The team ensures internal processes remain aligned with regulatory expectations and management intent, and it strengthens organizational discipline by embedding decision rights, controls, documentation norms, and review mechanisms into day-to-day operations.", "Compliance"),
    ("Regulatory Reporting Team", "Within the Compliance department, the Regulatory Reporting Team is responsible for preparing, validating, and submitting accurate and timely reports to RBI and other regulatory authorities, making it a critical link between the organization and external regulators. It works closely with Finance, Risk, Operations, Technology, and Data teams to gather the required inputs, reconcile figures, validate completeness, and ensure every submission is backed by reliable source data and documented sign-offs. Beyond filing reports, the team helps the organization maintain credibility with regulators by establishing reporting calendars, enforcing quality checks, responding to regulatory queries, and ensuring reporting obligations are fulfilled without delay or error.", "Compliance"),
    ("Enterprise Risk Team", "Within the Risk department, the Enterprise Risk Team provides an organization-wide view of strategic, financial, operational, compliance, and reputational risks so leadership can make informed and balanced decisions. It develops the enterprise risk management framework, defines risk appetite and thresholds, coordinates risk assessments across departments, and consolidates emerging risks into actionable insights for senior management and governance forums. By partnering with business, Finance, Compliance, Technology, Operations, HR, and Strategy teams, it helps the organization anticipate threats, prioritize mitigation plans, improve resilience, and pursue growth with a clearer understanding of downside exposure.", "Risk"),
    ("Credit Risk Team", "Within the Risk department, the Credit Risk Team safeguards the quality of the organization's lending or credit exposure by assessing borrower risk, defining underwriting standards, and monitoring portfolio performance against approved risk appetite. It works with Product, Sales, Operations, Finance, Compliance, and Data teams to design lending policies, set exposure limits, monitor delinquency trends, and identify early warning signals that could affect asset quality or regulatory compliance. In the broader organizational context, this team enables sustainable growth by ensuring commercial expansion is supported by disciplined credit decisioning, prudent portfolio management, and strong adherence to lending norms.", "Risk"),
    ("Operational Risk Team", "Within the Risk department, the Operational Risk Team focuses on risks arising from internal processes, systems, people, and external disruption, helping the organization reduce failures that can impact service quality, compliance, cost, or reputation. It partners with Operations, Technology, Information Security, HR, Compliance, and business teams to identify control gaps, track incidents and near misses, conduct root cause analysis, and strengthen preventive and detective controls across critical workflows. By embedding operational risk discipline into everyday execution, the team improves resilience, supports business continuity, and helps the organization scale without losing control over process integrity.", "Risk"),
    ("Legal Advisory Team", "Within the Legal department, the Legal Advisory Team provides the organization with formal legal interpretation on regulations, contracts, corporate matters, disputes, and business decisions so that every function can operate within a sound legal framework. It supports Compliance, Product, Sales, HR, Operations, Finance, and leadership teams by clarifying legal obligations, reviewing proposed actions, assessing legal exposure, and advising on how to structure decisions in a defensible manner. In the wider organizational context, this team reduces legal uncertainty, protects the company's interests, and enables growth initiatives to move forward with stronger legal confidence and control.", "Legal"),
    ("Contract Management Team", "Within the Legal department, the Contract Management Team manages the lifecycle of agreements with vendors, clients, partners, and service providers to ensure commercial relationships are documented clearly and protected appropriately. It drafts, reviews, negotiates, and tracks contracts in coordination with Procurement, Sales, Product, Compliance, Finance, Operations, and Technology teams, making sure obligations, service levels, liability terms, data protection clauses, and regulatory requirements are reflected properly. By standardizing contract practices and monitoring renewals, amendments, and compliance obligations, the team helps the organization reduce legal risk, avoid operational disputes, and maintain stronger governance over third-party and client commitments.", "Legal"),
    ("Financial Accounting Team", "Within the Finance department, the Financial Accounting Team is responsible for maintaining the integrity of the organization's books and records through accurate accounting, reconciliations, close processes, and financial statement preparation. It works closely with Operations, Treasury, Taxation, Compliance, business units, and auditors to capture transactions correctly, apply accounting standards, resolve exceptions, and ensure management and statutory reports reflect the true financial position of the company. In the context of the full organization, this team provides the financial discipline and transparency needed for decision-making, investor confidence, regulatory compliance, and long-term sustainability.", "Finance"),
    ("Treasury Team", "Within the Finance department, the Treasury Team manages the organization's liquidity, cash flow, banking relationships, investments, and funding position so the business always has the financial capacity to meet obligations and pursue growth. It coordinates with Financial Accounting, Operations, leadership, and business teams to forecast cash requirements, optimize fund deployment, monitor inflows and outflows, and maintain compliance with financial and regulatory constraints. At an enterprise level, the team plays a strategic role in balancing safety, liquidity, and returns, ensuring capital is used efficiently while protecting the organization's financial stability.", "Finance"),
    ("Taxation Team", "Within the Finance department, the Taxation Team ensures the organization meets all direct and indirect tax obligations accurately and on time while also supporting efficient tax planning within legal boundaries. It collaborates with Financial Accounting, Legal, Compliance, Procurement, Operations, and business teams to review transaction structures, prepare filings, manage assessments, maintain documentation, and address tax queries or disputes. In the broader organizational context, this team protects the company from penalties, supports sound financial planning, and ensures commercial activity is executed with full awareness of tax implications and compliance requirements.", "Finance"),
    ("Core Operations Team", "Within the Operations department, the Core Operations Team runs the day-to-day engine of the organization by executing transactions, settlements, reconciliations, account maintenance, and exception handling with accuracy and speed. It works alongside Finance, Compliance, Risk, Technology, customer-facing teams, and business stakeholders to ensure operational workflows are completed correctly, customer commitments are fulfilled, and service disruptions are minimized. As a central execution layer for the enterprise, this team turns policies and business decisions into consistent operational outcomes, making it essential to service reliability, control effectiveness, and organizational scalability.", "Operations"),
    ("Process Excellence Team", "Within the Operations department, the Process Excellence Team improves how the organization works by studying end-to-end workflows, identifying inefficiencies, and redesigning processes for better speed, control, quality, and scalability. It collaborates with Operations, Technology, Data, Compliance, Product, HR, and customer-facing teams to drive automation, standardization, process simplification, and measurable performance improvement across functions. In the context of the full organization, this team acts as a transformation enabler that helps reduce cost, improve turnaround times, strengthen controls, and create more efficient operating models that support business growth.", "Operations"),
    ("Customer Operations Team", "Within the Operations department, the Customer Operations Team manages the operational aspects of the customer lifecycle, including onboarding, verification, servicing, fulfillment support, and issue coordination, so customers can move smoothly through the organization's processes. It works closely with Sales, Customer Support, Compliance, Risk, Product, Technology, and Core Operations teams to ensure that customer requests are handled accurately, policies are followed, and handoffs between functions are seamless. From an enterprise perspective, this team plays a vital role in converting customer intent into successful operational delivery while protecting service quality, compliance, and turnaround commitments.", "Operations"),
    ("IT Infrastructure Team", "Within the Technology department, the IT Infrastructure Team provides the foundational technology backbone that keeps the organization running by managing servers, networks, cloud environments, devices, backups, monitoring, and platform reliability. It supports every department across the enterprise by ensuring systems are available, performant, secure, and recoverable, while also planning capacity, resilience, and disaster recovery for critical business operations. In the broader organizational context, this team enables productivity, business continuity, and digital scale by making sure the core technology environment can reliably support employees, applications, data, and customer services.", "Technology"),
    ("Application Development Team", "Within the Technology department, the Application Development Team designs, builds, enhances, and maintains the software applications that support internal operations, customer journeys, and strategic business capabilities. It partners with Product, Operations, Sales, Finance, Compliance, Data, and Customer Experience teams to translate business requirements into scalable features, integrations, and system improvements that align with organizational priorities. By managing the software development lifecycle from design to release and maintenance, this team helps the organization innovate faster, automate critical processes, and deliver more consistent digital experiences.", "Technology"),
    ("Information Security Team", "Within the Technology department, the Information Security Team protects the organization's systems, data, identities, and digital assets from cyber threats, unauthorized access, and security breaches. It works across all departments to establish security policies, access controls, monitoring practices, incident response plans, awareness programs, and third-party security reviews, ensuring security is embedded into operations, product development, vendor management, and employee behavior. At an organizational level, this team is essential for preserving trust, meeting regulatory and contractual obligations, and allowing the company to grow digitally without compromising confidentiality, integrity, or availability.", "Technology"),
    ("Data Engineering Team", "Within the Data department, the Data Engineering Team builds and maintains the pipelines, storage platforms, integration layers, and data architecture that allow the organization to collect, process, and govern information at scale. It works with Technology, Operations, Finance, Risk, Product, and Business Intelligence teams to ensure data from multiple systems is reliable, structured, accessible, and ready for reporting, analytics, and automation. In the broader organizational context, this team provides the technical foundation for data-driven decision-making by making enterprise data more usable, trustworthy, and scalable across departments.", "Data"),
    ("Business Intelligence Team", "Within the Data department, the Business Intelligence Team converts enterprise data into dashboards, reports, scorecards, and performance insights that help leaders and teams make better operational and strategic decisions. It collaborates with Finance, Risk, Operations, Product, Sales, HR, and Customer Experience teams to define key metrics, automate reporting, improve visibility into trends, and create a consistent view of business performance across the organization. By turning raw data into practical management information, this team helps the enterprise improve accountability, identify issues early, and align decisions with measurable outcomes.", "Data"),
    ("Data Science Team", "Within the Data department, the Data Science Team develops predictive models, forecasting tools, optimization algorithms, and AI-driven solutions that help the organization solve complex business problems more intelligently. It partners with Product, Risk, Sales, Operations, Finance, and Customer Experience teams to uncover patterns in data, improve decision quality, and embed advanced analytics into products, processes, and management workflows. In the larger organizational context, this team creates competitive advantage by using data not only to explain what has happened, but also to predict what is likely to happen and recommend what the business should do next.", "Data"),
    ("Talent Acquisition Team", "Within the HR department, the Talent Acquisition Team ensures the organization can attract and hire the talent required to meet its current needs and long-term growth plans. It works closely with business leaders and functional heads across Technology, Operations, Risk, Finance, Product, Sales, and Customer Experience to understand capability gaps, define hiring priorities, manage sourcing strategies, and deliver a strong candidate and onboarding experience. At an enterprise level, this team shapes workforce quality and organizational capacity by bringing in people whose skills, values, and potential align with the company's strategy and culture.", "HR"),
    ("Learning & Development Team", "Within the HR department, the Learning & Development Team strengthens organizational capability by designing training programs, leadership development initiatives, compliance learning, and role-based skill building for employees across the company. It partners with department heads and subject matter experts to identify capability gaps, support change management, and create learning pathways that improve individual performance as well as team readiness for future business needs. In the broader organizational context, this team helps the company remain adaptable, productive, and competitive by continuously investing in employee growth and institutional knowledge.", "HR"),
    ("HR Operations Team", "Within the HR department, the HR Operations Team manages the administrative and compliance backbone of the employee lifecycle, including payroll, employee records, attendance, benefits, policy administration, and labor law compliance. It supports employees and managers across the organization by ensuring people processes are accurate, timely, confidential, and well governed, while also maintaining reliable workforce data for decision-making and audit needs. From an enterprise perspective, this team creates consistency and trust in how the organization manages its people, making it essential to operational stability and employee experience.", "HR"),
    ("Customer Support Team", "Within the Customer Experience department, the Customer Support Team acts as the organization's frontline response unit for customer questions, complaints, service requests, and issue resolution across channels such as phone, email, chat, or ticketing platforms. It coordinates closely with Operations, Product, Technology, Compliance, Sales, and Customer Operations teams to resolve concerns quickly, communicate clearly, and ensure customers receive timely and accurate support. In the wider organizational context, this team protects customer trust, reduces churn, and provides valuable real-world feedback that can be used to improve products, processes, and service standards.", "Customer Experience"),
    ("Customer Experience Team", "Within the Customer Experience department, the Customer Experience Team looks beyond individual support interactions to improve the end-to-end customer journey across awareness, onboarding, servicing, issue resolution, and retention. It works with Product, Operations, Sales, Technology, Compliance, and Customer Support teams to identify pain points, measure satisfaction, redesign service moments, and embed customer-centric standards into the way the organization operates. At an enterprise level, this team helps turn customer feedback into strategic improvement, ensuring the organization grows not only by acquiring customers, but also by retaining them through better experiences.", "Customer Experience"),
    ("Product Strategy Team", "Within the Product department, the Product Strategy Team defines the product vision, roadmap priorities, market positioning, and investment focus that connect customer needs with the organization's business goals. It collaborates with Sales, Operations, Technology, Data, Finance, Compliance, and Strategy teams to evaluate opportunities, assess feasibility, understand market and regulatory dynamics, and decide which product capabilities should be built or expanded. In the context of the full organization, this team ensures product decisions are not isolated features, but coordinated bets that support revenue growth, competitive differentiation, operational readiness, and long-term strategic direction.", "Product"),
    ("Product Operations Team", "Within the Product department, the Product Operations Team ensures that product ideas are translated into well-governed execution by managing release readiness, cross-functional coordination, lifecycle processes, and operational support for launches and enhancements. It works across Product, Technology, Operations, Customer Experience, Sales, Compliance, and Data teams to align timelines, manage dependencies, track issues, and measure post-release performance and adoption. In the broader organizational context, this team provides the structure that allows products to scale smoothly, reducing execution friction and ensuring new capabilities are introduced in a controlled and business-ready manner.", "Product"),
    ("Sales Team", "Within the Sales department, the Sales Team drives revenue growth by identifying opportunities, acquiring clients, managing relationships, and converting market demand into sustainable business for the organization. It collaborates with Product, Customer Operations, Finance, Legal, Compliance, and Customer Experience teams to ensure that what is sold is commercially sound, operationally deliverable, and aligned with company strategy and risk standards. At an enterprise level, this team is a primary engine of growth, bringing in new business while also providing market feedback that shapes products, service models, and expansion priorities.", "Sales"),
    ("Internal Audit Team", "Within the Audit department, the Internal Audit Team provides independent assurance on whether the organization's controls, governance practices, risk management processes, and policy compliance are functioning effectively across departments. It reviews activities across Finance, Operations, Risk, Compliance, Technology, HR, Product, and customer-facing functions, identifies gaps, recommends corrective actions, and tracks remediation to closure. In the larger organizational context, this team strengthens accountability and transparency by giving leadership and governance bodies an objective view of how well the enterprise is managing risk and adhering to its own standards.", "Audit"),
    ("Corporate Strategy Team", "Within the Strategy department, the Corporate Strategy Team shapes the organization's long-term direction by evaluating growth opportunities, market expansion, transformation priorities, partnerships, and enterprise-wide strategic initiatives. It works with leadership and every major department, including Finance, Product, Sales, Risk, Operations, Technology, and HR, to align investments, assess competitive positioning, define strategic choices, and translate ambition into coordinated execution plans. In the broader organizational context, this team ensures the company is not only operating effectively today, but also building the capabilities, structure, and priorities needed for future relevance and sustainable growth.", "Strategy"),
]


def main():
    parser = argparse.ArgumentParser(description="Seed intel_teams collection")
    parser.add_argument("--clear", action="store_true", help="Drop existing intel_teams before inserting")
    args = parser.parse_args()

    store = IntelTeamStore()

    if args.clear:
        store._col.delete_many({})
        print("Cleared existing intel_teams.")

    existing_names = {t.name for t in store.list()}
    inserted = 0
    skipped = 0

    for name, function, department in TEAMS:
        if name in existing_names:
            print(f"  SKIP (exists): {name}")
            skipped += 1
            continue
        team = IntelTeam.new(name=name, function=function, department=department)
        store.create(team)
        print(f"  INSERT: {name} [{department}]")
        inserted += 1

    print(f"\nDone. {inserted} inserted, {skipped} skipped.")


if __name__ == "__main__":
    main()
