"use client";

import { useMutation, useQuery } from "convex/react";
import { useState } from "react";
import { toast } from "sonner";

// IMPORTANT: this import resolves only after running `npx convex dev` (or
// `npx convex codegen`) inside the convex_qwerty/ folder. See
// qwerty_mode/README.md for setup steps.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — generated by convex at deploy time
import { api } from "../../../../convex_qwerty/_generated/api";

import {
    qwertyIngest,
    qwertyQuery,
    qwertyFileUrl,
    type QwertyAnswer,
    type QwertyCitation,
} from "@/lib/qwerty/api";
import QwertyViewer from "./QwertyViewer";

interface ChatTurn {
    question: string;
    answer: QwertyAnswer | null;
    pending: boolean;
    error?: string;
}

export default function QwertyPage() {
    const files = useQuery(api.files.list, {}) ?? [];
    const conversations = useQuery(api.conversations.list, {}) ?? [];
    const createConversation = useMutation(api.conversations.create);

    const [activeConvId, setActiveConvId] = useState<string | null>(null);
    const messages = useQuery(
        api.messages.byConversation,
        activeConvId ? { conversationId: activeConvId } : "skip",
    ) ?? [];

    const [turns, setTurns] = useState<ChatTurn[]>([]);
    const [question, setQuestion] = useState("");
    const [pendingIngest, setPendingIngest] = useState(false);

    const [viewerUrl, setViewerUrl] = useState<string | null>(null);
    const [viewerPage, setViewerPage] = useState(1);

    async function handleUpload(e: React.ChangeEvent<HTMLInputElement>) {
        const file = e.target.files?.[0];
        if (!file) return;
        setPendingIngest(true);
        try {
            const r = await qwertyIngest(file);
            toast.success(`Ingested ${r.filename} — ${r.chunk_count} chunks`);
        } catch (err) {
            toast.error((err as Error).message);
        } finally {
            setPendingIngest(false);
            e.target.value = "";
        }
    }

    async function handleAsk() {
        const q = question.trim();
        if (!q) return;
        setQuestion("");
        const turn: ChatTurn = { question: q, answer: null, pending: true };
        setTurns((t) => [...t, turn]);
        try {
            const ans = await qwertyQuery(q);
            setTurns((t) =>
                t.map((row) => (row === turn ? { ...row, pending: false, answer: ans } : row)),
            );
        } catch (err) {
            setTurns((t) =>
                t.map((row) =>
                    row === turn ? { ...row, pending: false, error: (err as Error).message } : row,
                ),
            );
        }
    }

    async function handleCitation(c: QwertyCitation) {
        try {
            const url = await qwertyFileUrl(c.file_id, c.filename);
            setViewerUrl(url);
            setViewerPage(c.page_start || 1);
        } catch (err) {
            toast.error((err as Error).message);
        }
    }

    return (
        <div style={{ display: "grid", gridTemplateColumns: "260px 1fr 1fr", height: "100vh" }}>
            {/* Sidebar: files */}
            <aside style={{ borderRight: "1px solid #e5e7eb", padding: 16, overflowY: "auto" }}>
                <h2 style={{ fontSize: 14, fontWeight: 600, marginBottom: 12 }}>Qwerty Mode · Files</h2>
                <label
                    style={{
                        display: "block",
                        padding: 12,
                        border: "1px dashed #9ca3af",
                        borderRadius: 8,
                        textAlign: "center",
                        cursor: pendingIngest ? "wait" : "pointer",
                        marginBottom: 16,
                        fontSize: 13,
                    }}
                >
                    {pendingIngest ? "Ingesting…" : "Upload PDF"}
                    <input
                        type="file"
                        accept="application/pdf"
                        onChange={handleUpload}
                        disabled={pendingIngest}
                        style={{ display: "none" }}
                    />
                </label>
                <ul style={{ listStyle: "none", padding: 0, margin: 0, fontSize: 13 }}>
                    {files.map((f: any) => (
                        <li key={f._id} style={{ padding: "6px 4px", borderBottom: "1px solid #f3f4f6" }}>
                            <div style={{ fontWeight: 500 }}>{f.filename}</div>
                            <div style={{ color: "#6b7280", fontSize: 11 }}>
                                {f.pageCount} pages · {f.chunkCount} chunks
                            </div>
                        </li>
                    ))}
                    {files.length === 0 && <li style={{ color: "#9ca3af" }}>No files yet.</li>}
                </ul>
            </aside>

            {/* Center: chat */}
            <main style={{ display: "flex", flexDirection: "column", borderRight: "1px solid #e5e7eb" }}>
                <div style={{ flex: 1, overflowY: "auto", padding: 16 }}>
                    {turns.length === 0 && (
                        <p style={{ color: "#6b7280" }}>
                            Upload a PDF on the left, then ask a question. Citations are clickable
                            and jump to the source page on the right.
                        </p>
                    )}
                    {turns.map((t, i) => (
                        <div key={i} style={{ marginBottom: 24 }}>
                            <div style={{ fontWeight: 600, marginBottom: 6 }}>You</div>
                            <div style={{ marginBottom: 12 }}>{t.question}</div>
                            <div style={{ fontWeight: 600, marginBottom: 6 }}>Govinda · Qwerty</div>
                            {t.pending && <div style={{ color: "#6b7280" }}>Thinking…</div>}
                            {t.error && <div style={{ color: "#b91c1c" }}>{t.error}</div>}
                            {t.answer && (
                                <>
                                    <div style={{ whiteSpace: "pre-wrap", marginBottom: 12 }}>
                                        {t.answer.text}
                                    </div>
                                    {t.answer.citations.length > 0 && (
                                        <ol style={{ paddingLeft: 20, fontSize: 13, color: "#374151" }}>
                                            {t.answer.citations.map((c) => (
                                                <li key={c.chunk_id} style={{ marginBottom: 6 }}>
                                                    <button
                                                        type="button"
                                                        onClick={() => handleCitation(c)}
                                                        style={{
                                                            background: "none",
                                                            border: 0,
                                                            color: "#2563eb",
                                                            cursor: "pointer",
                                                            padding: 0,
                                                            font: "inherit",
                                                            textAlign: "left",
                                                        }}
                                                    >
                                                        {c.citation_id} {c.filename} · p.{c.page_start}
                                                    </button>
                                                    <div style={{ color: "#6b7280", fontSize: 12 }}>
                                                        {c.excerpt}
                                                    </div>
                                                </li>
                                            ))}
                                        </ol>
                                    )}
                                </>
                            )}
                        </div>
                    ))}
                </div>
                <div style={{ borderTop: "1px solid #e5e7eb", padding: 12, display: "flex", gap: 8 }}>
                    <input
                        type="text"
                        value={question}
                        onChange={(e) => setQuestion(e.target.value)}
                        onKeyDown={(e) => {
                            if (e.key === "Enter" && !e.shiftKey) {
                                e.preventDefault();
                                handleAsk();
                            }
                        }}
                        placeholder="Ask about the uploaded documents…"
                        style={{
                            flex: 1,
                            padding: "8px 10px",
                            borderRadius: 6,
                            border: "1px solid #d1d5db",
                            font: "inherit",
                        }}
                    />
                    <button
                        type="button"
                        onClick={handleAsk}
                        style={{
                            padding: "8px 14px",
                            background: "#111827",
                            color: "white",
                            border: 0,
                            borderRadius: 6,
                            cursor: "pointer",
                        }}
                    >
                        Ask
                    </button>
                </div>
            </main>

            {/* Right: PDF viewer */}
            <section>
                <QwertyViewer url={viewerUrl} page={viewerPage} />
            </section>
        </div>
    );
}
